version: '3'
services:
  app:
    build: .
    volumes:
      - .:/src/react-html-snapshot-sample
      - node_modules:/src/react-html-snapshot-sample/node_modules:delegated
    command: tail -f /dev/null
volumes: 
  node_modules: